name: VIPM CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install-packages:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Docker
        run: Start-Service docker

      - name: Pull LabVIEW container image
        run: docker pull nationalinstruments/labview:latest-windows

      - name: Check CLI
        run: >
          docker run --rm
          nationalinstruments/labview:latest-windows
          LabVIEWCLI -Help -Headless
          
          docker run --rm
          nationalinstruments/labview:latest-windows
          vipm version


      